[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "gcc-unwrapped"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmd = "python main.py"
